---
title: "GES 678: Week 10"
subtitle: "Cost-Benefits and Cost Avoidance"
format: 
  pdf:
    toc: true
date: "11-12-2025"
---

{{< pagebreak >}}

# Lecture

## Types of benefits

-   Monetary
    -   Cost Savings
        -   Reduce current expenses
        -   "Doing more with less"
    -   Cost Avoidance
        -   Replacement of intensive processes with ones that are more efficient
        -   Better results with same resources
    -   Revenue Generation
        -   New products
        -   Efficiencies in creation of products
-   Efficiency
    -   Productivity
    -   Outputs
-   Qualitative

### Cost-Benefit Model

-   Identify cost by year
-   Benefits by year
    -   Savings
    -   Benefits to organization
    -   Future/external benefits
    -   Cost avoidance
-   Compare benefits and costs
-   Calculate cost/benefit ratio

#### Efficiencies Benefits

-   Productivity
    -   Output more results with current resources
-   Outputs
    -   Reduce time to create products
    -   Reduction or removal of workflows

#### Qualitative benefits

-   Immeasurable benefits
    -   Job satisfaction
-   Positive impact on workflows and operations
-   Improved decision-making
-   Quality of service

### Suggestions/reminders

-   Take projections as far as necessary
-   Estimate and document intangibles
-   Include costs of new demands (e.g. regulation) on organization and savings

### Cost Avoidance

-   Resource allocation to other tasks
    -   People
        -   Reassigned
        -   Trained to new functions
        -   e.g. field collection staff -> GIS techs or analysts
    -   Funding
        -   Transfer funds from retired functions to pay for new capability
        -   e.g. maintenance of older software to pay for new modules
-   Find efficiencies in processes
    -   Removal of steps
        -   Remove redundancy
        -   Streamlined process
        -   e.g. print and then scan documents
    -   Shorten durations  
        -   Less steps can be shorter duration workflows
        -   Automation of workflows
-   Retired processes
    -   Retire unused or unnecessary processes
        -   Tasks no longer needed
-   Software/data/licensing costs
    -   Often higher costs to support older software
    -   Reduce costs to procure data when data is generated by a new process
        -   Business data purchase is removed by GIS integration with permitting system
        
## Funding Sources

### Government Grants

-   Federal - FEMA, HUD, DOT
-   State - DNR
-   Local/Regional

-   GIS strengthens proposals by showing accountability and efficiency
    -   Hazard mitigation or infrastructure projects

### Return on investment

**The measure of the financial and operational benefits gained compared to the costs of implementing and maintaining the system.**

Bottom line: *is the GIS program worth the time, money, resources spent on the implementation and ongoing costs?*

-   ROI analysis demonstrates cost savings and efficiency gains
-   Evidence-based approach gains leadership buy-in
    -   Reduced duplication of services
    
### Cost sharing

-   Shared costs across departments
-   Multiple departments benefit
-   Shared costs reduce duplication
-   Promotes enterprise-wide adoption

### Partnerships

-   Collaborations with utilities, universities, nonprofits
-   Access to additional funding and expertise
    -   Joint ventures with university providers
    
### Programmatic Approach

-   Treat GIS as a program, not a one-off project
-   Governance ensures sustainability and accountability
-   Secures ongoing operational funding